# This file was generated by GoReleaser. DO NOT EDIT.
cask "panel" do
  name "panel"
  desc "A second opinion is good. A panel of experts is better."
  homepage "https://github.com/codebeauty/panel"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "panel"

  on_macos do
    on_intel do
      url "https://github.com/codebeauty/panel/releases/download/v#{version}/panel_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/codebeauty/panel/releases/download"
      sha256 "e8cb20b99ea1a4fd56d812c0937233a949515376706397aee8957a01e8dcb207"
    end
    on_arm do
      url "https://github.com/codebeauty/panel/releases/download/v#{version}/panel_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/codebeauty/panel/releases/download"
      sha256 "060eefe16f453d6a89f8227757762635745047fad8ce8f0dc10a6a79e084e1d5"
    end
  end

  # No zap stanza required
end
