# This file was generated by GoReleaser. DO NOT EDIT.
cask "panel" do
  name "panel"
  desc "A second opinion is good. A panel of experts is better."
  homepage "https://github.com/codebeauty/panel"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "panel"

  on_macos do
    on_intel do
      url "https://github.com/codebeauty/panel/releases/download/v#{version}/panel_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/codebeauty/panel/releases/download"
      sha256 "e0b515c79b6680dcd0a8e84aac38edba75a592777903ca883af710bec53cfbdd"
    end
    on_arm do
      url "https://github.com/codebeauty/panel/releases/download/v#{version}/panel_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/codebeauty/panel/releases/download"
      sha256 "cc1878f6b9dab232426a28306279512f5f7c17704ebb376ac7b5987d85eafdc7"
    end
  end

  # No zap stanza required
end
