# This file was generated by GoReleaser. DO NOT EDIT.
cask "panel" do
  name "panel"
  desc "Fan out prompts to multiple AI coding agents in parallel"
  homepage "https://github.com/codebeauty/panel"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "panel"

  on_macos do
    on_intel do
      url "https://github.com/codebeauty/panel/releases/download/v#{version}/panel_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/codebeauty/panel/releases/download"
      sha256 "7330123c2a56f9d59b7fca205f1154ce134336614a027407f8080059820061ff"
    end
    on_arm do
      url "https://github.com/codebeauty/panel/releases/download/v#{version}/panel_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/codebeauty/panel/releases/download"
      sha256 "2485de72618e6d4e5a71a6b636b74f07a936d0daf347de3aef21011747d48cc0"
    end
  end

  # No zap stanza required
end
