# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Panel < Formula
  desc "A second opinion is good. A panel of experts is better."
  homepage "https://github.com/codebeauty/panel"
  version "0.1.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/codebeauty/panel/releases/download/v0.1.3/panel_0.1.3_darwin_amd64.tar.gz"
    sha256 "db6a23ba83143ab10d505f29fcc1f8f8c974e35ae67f9a8227110eafc1eafa9e"

    define_method(:install) do
      bin.install "panel"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/codebeauty/panel/releases/download/v0.1.3/panel_0.1.3_darwin_arm64.tar.gz"
    sha256 "c179608d0bf8fc2e7ef41664d36724444eb22cfd82f4fe94fa90a1571e28f7db"

    define_method(:install) do
      bin.install "panel"
    end
  end
end
