# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Panel < Formula
  desc "A second opinion is good. A panel of experts is better."
  homepage "https://github.com/codebeauty/panel"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/codebeauty/panel/releases/download/v0.1.2/panel_0.1.2_darwin_amd64.tar.gz"
    sha256 "e8cb20b99ea1a4fd56d812c0937233a949515376706397aee8957a01e8dcb207"

    define_method(:install) do
      bin.install "panel"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/codebeauty/panel/releases/download/v0.1.2/panel_0.1.2_darwin_arm64.tar.gz"
    sha256 "060eefe16f453d6a89f8227757762635745047fad8ce8f0dc10a6a79e084e1d5"

    define_method(:install) do
      bin.install "panel"
    end
  end
end
