# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Panel < Formula
  desc "A second opinion is good. A panel of experts is better."
  homepage "https://github.com/codebeauty/panel"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/codebeauty/panel/releases/download/v0.1.1/panel_0.1.1_darwin_amd64.tar.gz"
    sha256 "e0b515c79b6680dcd0a8e84aac38edba75a592777903ca883af710bec53cfbdd"

    define_method(:install) do
      bin.install "panel"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/codebeauty/panel/releases/download/v0.1.1/panel_0.1.1_darwin_arm64.tar.gz"
    sha256 "cc1878f6b9dab232426a28306279512f5f7c17704ebb376ac7b5987d85eafdc7"

    define_method(:install) do
      bin.install "panel"
    end
  end
end
